apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-worker

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend-worker

  template:
    metadata:
      labels:
        app: backend-worker

    spec:
      initContainers:
        - name: wait-for-redis
          image: redis:7
          command: ["sh", "-c", "until redis-cli -h redis ping; do sleep 2; done"]

      containers:
        - name: backend-worker
          image: denysvivdenko/chatops-backend:88ddf319dacb1ae4f17f46a46a070dc025d58c6e
          env:
            - name: REDIS_HOST
              value: "redis"
          command: ["python", "-m", "chatops.workers.worker"]
