frontend:
  image:
    repository: denysvivdenko/chatops-frontend
    tag: "81e54164fc3eaf89f644bc0ff93f66d5c2ea8d85"
    pullPolicy: Always
  backendUrl: "https://chatops.denysvivdenko.dev/api"

backend:
  image:
    repository: denysvivdenko/chatops-backend
    tag: "5d5548b8953379b83535ad95a1459ceb9489ba1b"
    pullPolicy: Always

redis:
  storage: 1Gi

mongodb:
  storage: 1Gi
