frontend:
  image:
    repository: denysvivdenko/chatops-frontend
    tag: "589a1ed9a7e54d6ec7a9ea004bdd39d382b02a50"
    pullPolicy: Always
  backendUrl: "https://chatops.denysvivdenko.dev/api"

backend:
  image:
    repository: denysvivdenko/chatops-backend
    tag: "da26750996bc0aab4469a0f53a0436fd7747172f"
    pullPolicy: Always

redis:
  storage: 1Gi

mongodb:
  storage: 1Gi
