frontend:
  image:
    repository: denysvivdenko/chatops-frontend
    tag: "2d5345412611f09b41902fafa758d709e5163c10"
    pullPolicy: Always
  backendUrl: "https://nonaccusing-flynn-lurkingly.ngrok-free.dev/api"

backend:
  image:
    repository: denysvivdenko/chatops-backend
    tag: "a9e1cb1fb7a3aa8855bd07248a00a60f1ba68da6"
    pullPolicy: Always

redis:
  storage: 1Gi

mongodb:
  storage: 1Gi

ngrok:
  domain: "nonaccusing-flynn-lurkingly.ngrok-free.dev" 
