frontend:
  image:
    repository: denysvivdenko/chatops-frontend
    tag: "2d5345412611f09b41902fafa758d709e5163c10"
    pullPolicy: Always
  backendUrl: "https://nonaccusing-flynn-lurkingly.ngrok-free.dev/api"

backend:
  image:
    repository: denysvivdenko/chatops-backend
    tag: "57242c304a4726fe4389841897f24b02808fb85a"
    pullPolicy: Always

redis:
  storage: 1Gi

ngrok:
  domain: "nonaccusing-flynn-lurkingly.ngrok-free.dev" 
