frontend:
  image:
    repository: chatops-frontend
    tag: latest
    pullPolicy: Never
  backendUrl: "https://nonaccusing-flynn-lurkingly.ngrok-free.dev/api"

backend:
  image:
    repository: chatops-backend
    tag: latest
    pullPolicy: Never

ngrok:
  domain: "nonaccusing-flynn-lurkingly.ngrok-free.dev" 