frontend:
  image:
    repository: denysvivdenko/chatops-frontend
    tag: "6a05697fe81e93d0a552ce299fa124fce393c92e"
    pullPolicy: Always
  backendUrl: "https://nonaccusing-flynn-lurkingly.ngrok-free.dev/api"

backend:
  image:
    repository: denysvivdenko/chatops-backend
    tag: "88ddf319dacb1ae4f17f46a46a070dc025d58c6e"
    pullPolicy: Always

redis:
  storage: 1Gi

ngrok:
  domain: "nonaccusing-flynn-lurkingly.ngrok-free.dev" 