apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: denysvivdenko/chatops-frontend:6a05697fe81e93d0a552ce299fa124fce393c92e
          env:
            - name: BACKEND_URL
              value: "http://192.168.1.56/api"
          ports:
            - containerPort: 3000