apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: denysvivdenko/chatops-frontend:7f26098e696e6a7826db2cec01b545802a50e191
          ports:
            - containerPort: 3000