apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: chatops-app
  namespace: argocd

spec:
  project: chatops

  source:
    repoURL: https://github.com/denisvivdenko/chatops-infra-base.git
    path: charts/chatops
    targetRevision: HEAD

    helm:
      valueFiles:
        - values.yaml

  destination:
    name: in-cluster
    namespace: dev